using FairWorkly.Domain.Payroll.Entities;

namespace FairWorkly.Application.Payroll.Interfaces;

/// <summary>
/// Repository for Payslip entity operations
/// </summary>
public interface IPayslipRepository
{
    /// <summary>
    /// Adds multiple Payslips to the database
    /// Note: After calling this method, the Payslips will have their Ids generated by EF Core
    /// </summary>
    /// <param name="payslips">The payslips to add</param>
    /// <param name="cancellationToken">Cancellation token</param>
    Task AddRangeAsync(IEnumerable<Payslip> payslips, CancellationToken cancellationToken = default);

    /// <summary>
    /// Saves all pending changes to the database
    /// </summary>
    /// <param name="cancellationToken">Cancellation token</param>
    Task SaveChangesAsync(CancellationToken cancellationToken = default);
}
